### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by cvalencia1991**
# In this milestone, I did the following activities:

-accessibility problems

-Added clear value for alt in every image
-Edit the tab index for each structure in HTML 
 -Tested Linters file to lint my HTML and CSS file

Also, I check the next requires 

Page title: no issue found.
Image text alternatives: no issue found
Text heading: [Edit the Headers in the about me and the cards sections](https://github.com/cvalencia1991/Portafolio/pull/10/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L105-L193)
Color Contrast: c[hanges color contrast in hex to HSL of each color in the CSS](https://github.com/cvalencia1991/Portafolio/pull/10/files#diff-380b7b38760dd442e897eb0164c58f6a17da966ccaca6318017a468c163979b1L8-L1342)
Resize: no Resize issue found
Interaction: [Add Area labels on each form that use to fill the survey form like name and email address](https://github.com/cvalencia1991/Portafolio/pull/10/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L32-L232)
Moving content: no issue found.
Multi-media: no issue found.
The basic structure of the page: no issue found.

### CODE REVIEW

**Review by Munsa1 — CHANGES_REQUESTED** [review]
Hi @cvalencia1991, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._
- It's a requirement that you list all the points that you've checked

Your Pull Request Description
image

The Required Checks
image
### Note to indicate If for some checks no issues were found
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cvalencia1991** [comment]
ok im going to edit the comment on pull request

**Review by mahbubul14 — APPROVED** [review]
# Project Approved :trophy: :tada: 

Hi @cvalencia1991 , 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive pull request.
:heavy_check_mark: Well implemented suggested changes.

### Optional suggestions :arrow_down_small: 

- [ ]  Currently, your `README` file is not updated according to the project. Please update your `README` file. You can use [this template ](https://github.com/microverseinc/readme-template)for the `README` but remember to customize it to your project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by cvalencia1991** [comment]
ok I'm going to edit the README.md file

**Pull request merged**
